name: Publish Astro Website to GitHub Pages

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the action

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build Website
        run: yarn build # Change this to the build command specific to your Astro project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Change to the name of your secret
          publish_dir: ./dist # Change this to the directory where your Astro website is built
